### ISSUE TITLE
Desenvolver a funcionalidade de autenticação de usuário.

### ISSUE THREAD

**Issue by proffbgoncalves** [proffbgoncalves/portal_eclb#16]
## Objetivo do Épico
Desenvolver a funcionalidade de autenticação de usuário.

### Tarefas
- [ ] Criar página de login (#1)
- [ ] Configurar autenticação no backend (#2)
- [ ] Implementar recuperação de senha (#3)
- [ ] Configurar integração com OAuth (#4)
